name: Build page
on: [workflow_dispatch]
jobs:
  push_to_registry:
    name: Push Docker images to GCR
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
