name: Build page
on: [workflow_dispatch]
permissions:
  contents: write
jobs:
  build_page:
    name: Build page
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npx tsc ./src/index.ts --outFile ./src/index.js
      - run: sed -i -e "s#CONTACT_ENDPOINT#$CONTACT_ENDPOINT#g" ./src/index.js
      - run: npx @11ty/eleventy
      - run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add ./public/*
          git commit -m build
          git push