name: Send daily test mail
on:
  schedule:
    - cron: '0 6 * * *'
env:
  CONTACT_ENDPOINT: ${{ vars.API_BELIEVEINTALKING }}
jobs:
  send_test_mail:
    name: Send test mail
    runs-on: ubuntu-latest
    steps:
      - name: run curl API gateway
        run: |
            curl --location $CONTACT_ENDPOINT \
            --header 'Content-Type: application/json' \
            --data '{
              "name":"Test",
              "email": "test@test",
              "message": "Test of day:\n\n '"$(date +"Date: %Y-%m-%d")"'"
            }'