name: Send daily test mail
on: [workflow_dispatch]
  # schedule:
  #   - cron:  '0 6 * * *'
jobs:
  send_test_mail:
    name: Send test mail
    runs-on: ubuntu-latest
    steps:
      - name: run curl API gateway
        run: |
            TZ=Europe/London
            curl --location 'https://6vepad8o23.execute-api.eu-central-1.amazonaws.com/default/ContactFormBelieveInTalking' \
            --header 'Content-Type: application/json' \
            --data '{
              "name":"Morning test",
              "email": "test@test",
              "message": "Goodmorning, this is the test of day:\n\n '"$(date +"Date: %Y-%m-%d TIME: %H:%M:%S")"'"
            }'