name: Send daily test mail
on: [workflow_dispatch]
  schedule:
      - cron:  '0 8 * * *'
jobs:
  send_test_mail:
    name: Send test mail
    runs-on: ubuntu-latest
    steps:
      - name: run curl API gateway
        run: |
            curl --location 'https://6vepad8o23.execute-api.eu-central-1.amazonaws.com/default/ContactFormBelieveInTalking' \
            --header 'Content-Type: application/json' \
            --data '{
              "name":"Test",
              "email": "test@test",
              "message": "Test of day:\n\n '"$(date +"Date: %Y-%m-%d")"'"
            }'
